import json


PUSH_HOOK_CALL_DATA = {
 u'after': u'56cc68f8c5f8774f4fd5a3cce075daa858b6ac6e',
 u'before': u'ff3a2c7478281db00c7f98156b33df7d3aa80a2a',
 u'commits': [{u'added': [],
               u'author': {u'email': u'anthony.romanovich@gmail.com',
                           u'name': u'Anton Romanovich',
                           u'username': u'aromanovich'},
               u'committer': {u'email': u'anthony.romanovich@gmail.com',
                              u'name': u'Anton Romanovich',
                              u'username': u'aromanovich'},
               u'distinct': True,
               u'id': u'6a55b64b3c3b94ffb4291a220e06ce7be9f3f2d2',
               u'message': u'Commit1',
               u'modified': [u'x'],
               u'removed': [],
               u'timestamp': u'2013-12-13T21:38:43-08:00',
               u'url': u'https://github.com/aromanovich/yearinpictures/commit/6a55b64b3c3b94ffb4291a220e06ce7be9f3f2d2'},
              {u'added': [],
               u'author': {u'email': u'anthony.romanovich@gmail.com',
                           u'name': u'Anton Romanovich',
                           u'username': u'aromanovich'},
               u'committer': {u'email': u'anthony.romanovich@gmail.com',
                              u'name': u'Anton Romanovich',
                              u'username': u'aromanovich'},
               u'distinct': True,
               u'id': u'47fe2c74f6d46304830ed46afd59a53401b20b78',
               u'message': u'Commit2',
               u'modified': [u'y'],
               u'removed': [],
               u'timestamp': u'2013-12-13T21:38:48-08:00',
               u'url': u'https://github.com/aromanovich/yearinpictures/commit/56cc68f8c5f8774f4fd5a3cce075daa858b6ac6e'}],
 u'compare': u'https://github.com/aromanovich/yearinpictures/compare/ff3a2c747828...56cc68f8c5f8',
 u'created': False,
 u'deleted': False,
 u'forced': False,
 u'head_commit': {u'added': [],
                  u'author': {u'email': u'anthony.romanovich@gmail.com',
                              u'name': u'Anton Romanovich',
                              u'username': u'aromanovich'},
                  u'committer': {u'email': u'anthony.romanovich@gmail.com',
                                 u'name': u'Anton Romanovich',
                                 u'username': u'aromanovich'},
                  u'distinct': True,
                  u'id': u'47fe2c74f6d46304830ed46afd59a53401b20b78',
                  u'message': u'Commit2',
                  u'modified': [u'y'],
                  u'removed': [],
                  u'timestamp': u'2013-12-13T21:38:48-08:00',
                  u'url': u'https://github.com/aromanovich/yearinpictures/commit/47fe2c74f6d46304830ed46afd59a53401b20b78'},
 u'pusher': {u'email': u'anthony.romanovich@gmail.com',
             u'name': u'aromanovich'},
 u'ref': u'refs/heads/master',
 u'repository': {u'created_at': 1348397294,
                 u'fork': False,
                 u'forks': 0,
                 u'has_downloads': True,
                 u'has_issues': True,
                 u'has_wiki': True,
                 u'id': 5921305,
                 u'language': u'JavaScript',
                 u'master_branch': u'master',
                 u'name': u'yearinpictures',
                 u'open_issues': 1,
                 u'owner': {u'email': u'anthony.romanovich@gmail.com',
                            u'name': u'aromanovich'},
                 u'private': True,
                 u'pushed_at': 1386999536,
                 u'size': 1892,
                 u'stargazers': 0,
                 u'url': u'https://github.com/aromanovich/yearinpictures',
                 u'watchers': 0}}

PUSH_HOOK_CALL_JSON = json.dumps(PUSH_HOOK_CALL_DATA)


USER_DATA = {
    u'avatar_url': u'https://2.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
    u'bio': None,
    u'blog': u'http://brainstorage.me/aromanovich ',
    u'company': None,
    u'created_at': u'2011-07-03T05:35:59Z',
    u'email': u'anthony.romanovich@gmail.com',
    u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
    u'followers': 8,
    u'followers_url': u'https://api.github.com/users/aromanovich/followers',
    u'following': 11,
    u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
    u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
    u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
    u'hireable': False,
    u'html_url': u'https://github.com/aromanovich',
    u'id': 891264,
    u'location': u'Russia, Ekaterinburg',
    u'login': u'aromanovich',
    u'name': u'Anton Romanovich',
    u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
    u'public_repos': 15,
    u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
    u'repos_url': u'https://api.github.com/users/aromanovich/repos',
    u'site_admin': False,
    u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
    u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
    u'type': u'User',
    u'updated_at': u'2013-11-01T10:31:40Z',
    u'url': u'https://api.github.com/users/aromanovich'
}

USER_JSON = json.dumps(USER_DATA)


DEPLOY_KEY_DATA = {
    'url': 'https://api.github.com/user/keys/10',
    'verified': True,
    'id': 495863,
    'key': '...',
    'title': 'key',
}

DEPLOY_KEY_JSON = json.dumps(DEPLOY_KEY_DATA)


HOOK_DATA = {
    u'name': u'web',
    u'url': u'https://api.github.com/repos/aromanovich/test/hooks/1455982',
    u'created_at': u'2013-11-10T08:36:33Z',
    u'updated_at': u'2013-11-10T08:36:33Z',
    u'test_url': u'https://api.github.com/repos/aromanovich/test/hooks/1455982/test',
    u'id': 1455982,
    u'active': True,
    u'config': {
        u'url': u'http://127.0.0.1:10001/_hooks/hook/1/',
        u'content_type': u'json'
    },
    u'events': [u'push', u'pull_request'],
    u'last_response': {
        u'status': u'unused',
        u'message': None,
        u'code': None
    },
}


COMMIT_47fe2_DATA = {
    u'author': {
        u'date': u'2013-11-12T18:31:07Z',
        u'email': u'anthony.romanovich@gmail.com',
        u'name': u'Anton Romanovich'
    },
    u'committer': {
        u'date': u'2013-11-12T18:31:07Z',
        u'email': u'anthony.romanovich@gmail.com',
        u'name': u'Anton Romanovich'
    },
    u'html_url': u'https://github.com/aromanovich/yearinpictures/commits/c5e3db14c8b3dee66470eca65bd2ebbd90969f6a',
    u'message': u'Just another commit',
    u'parents': [{
        u'html_url': u'https://github.com/aromanovich/yearinpictures/commits/47fe2c74f6d46304830ed46afd59a53401b20b78',
        u'sha': u'47fe2c74f6d46304830ed46afd59a53401b20b78',
        u'url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/commits/47fe2c74f6d46304830ed46afd59a53401b20b78'
    }],
    u'sha': u'47fe2c74f6d46304830ed46afd59a53401b20b78',
    u'tree': {
        u'sha': u'1caf942de8b983e68a3810ff08799e527f8795bf',
        u'url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/trees/1caf942de8b983e68a3810ff08799e527f8795bf'
    },
    u'url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/commits/c5e3db14c8b3dee66470eca65bd2ebbd90969f6a'
}
 

PULL_REQUEST_HOOK_CALL_DATA = {
 u'action': u'synchronize',
 u'number': 6,
 u'pull_request': {u'_links': {u'comments': {u'href': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/6/comments'},
                               u'html': {u'href': u'https://github.com/aromanovich/yearinpictures/pull/6'},
                               u'issue': {u'href': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/6'},
                               u'review_comments': {u'href': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls/6/comments'},
                               u'self': {u'href': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls/6'},
                               u'statuses': {u'href': u'https://api.github.com/repos/aromanovich/yearinpictures/statuses/47fe2c74f6d46304830ed46afd59a53401b20b78'}},
                   u'additions': 127,
                   u'assignee': None,
                   u'base': {u'label': u'aromanovich:master',
                             u'ref': u'master',
                             u'repo': {u'archive_url': u'https://api.github.com/repos/aromanovich/yearinpictures/{archive_format}{/ref}',
                                       u'assignees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/assignees{/user}',
                                       u'blobs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/blobs{/sha}',
                                       u'branches_url': u'https://api.github.com/repos/aromanovich/yearinpictures/branches{/branch}',
                                       u'clone_url': u'https://github.com/aromanovich/yearinpictures.git',
                                       u'collaborators_url': u'https://api.github.com/repos/aromanovich/yearinpictures/collaborators{/collaborator}',
                                       u'comments_url': u'https://api.github.com/repos/aromanovich/yearinpictures/comments{/number}',
                                       u'commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/commits{/sha}',
                                       u'compare_url': u'https://api.github.com/repos/aromanovich/yearinpictures/compare/{base}...{head}',
                                       u'contents_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contents/{+path}',
                                       u'contributors_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contributors',
                                       u'created_at': u'2012-09-23T10:48:14Z',
                                       u'default_branch': u'master',
                                       u'description': None,
                                       u'downloads_url': u'https://api.github.com/repos/aromanovich/yearinpictures/downloads',
                                       u'events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/events',
                                       u'fork': False,
                                       u'forks': 0,
                                       u'forks_count': 0,
                                       u'forks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/forks',
                                       u'full_name': u'aromanovich/yearinpictures',
                                       u'git_commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/commits{/sha}',
                                       u'git_refs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/refs{/sha}',
                                       u'git_tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/tags{/sha}',
                                       u'git_url': u'git://github.com/aromanovich/yearinpictures.git',
                                       u'has_downloads': True,
                                       u'has_issues': True,
                                       u'has_wiki': True,
                                       u'homepage': None,
                                       u'hooks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/hooks',
                                       u'html_url': u'https://github.com/aromanovich/yearinpictures',
                                       u'id': 5921305,
                                       u'issue_comment_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/comments/{number}',
                                       u'issue_events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/events{/number}',
                                       u'issues_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues{/number}',
                                       u'keys_url': u'https://api.github.com/repos/aromanovich/yearinpictures/keys{/key_id}',
                                       u'labels_url': u'https://api.github.com/repos/aromanovich/yearinpictures/labels{/name}',
                                       u'language': u'JavaScript',
                                       u'languages_url': u'https://api.github.com/repos/aromanovich/yearinpictures/languages',
                                       u'master_branch': u'master',
                                       u'merges_url': u'https://api.github.com/repos/aromanovich/yearinpictures/merges',
                                       u'milestones_url': u'https://api.github.com/repos/aromanovich/yearinpictures/milestones{/number}',
                                       u'mirror_url': None,
                                       u'name': u'yearinpictures',
                                       u'notifications_url': u'https://api.github.com/repos/aromanovich/yearinpictures/notifications{?since,all,participating}',
                                       u'open_issues': 1,
                                       u'open_issues_count': 1,
                                       u'owner': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                                                  u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                                                  u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                                                  u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                                                  u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                                                  u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                                                  u'html_url': u'https://github.com/aromanovich',
                                                  u'id': 891264,
                                                  u'login': u'aromanovich',
                                                  u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                                                  u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                                                  u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                                                  u'site_admin': False,
                                                  u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                                                  u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                                                  u'type': u'User',
                                                  u'url': u'https://api.github.com/users/aromanovich'},
                                       u'private': True,
                                       u'pulls_url': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls{/number}',
                                       u'pushed_at': u'2013-11-12T17:33:51Z',
                                       u'releases_url': u'https://api.github.com/repos/aromanovich/yearinpictures/releases{/id}',
                                       u'size': 2140,
                                       u'ssh_url': u'git@github.com:aromanovich/yearinpictures.git',
                                       u'stargazers_count': 0,
                                       u'stargazers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/stargazers',
                                       u'statuses_url': u'https://api.github.com/repos/aromanovich/yearinpictures/statuses/{sha}',
                                       u'subscribers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscribers',
                                       u'subscription_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscription',
                                       u'svn_url': u'https://github.com/aromanovich/yearinpictures',
                                       u'tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/tags',
                                       u'teams_url': u'https://api.github.com/repos/aromanovich/yearinpictures/teams',
                                       u'trees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/trees{/sha}',
                                       u'updated_at': u'2013-11-12T17:33:51Z',
                                       u'url': u'https://api.github.com/repos/aromanovich/yearinpictures',
                                       u'watchers': 0,
                                       u'watchers_count': 0},
                             u'sha': u'9db14c33e3bc0fb50ae539ea4ef4ea54804fda4d',
                             u'user': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                                       u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                                       u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                                       u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                                       u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                                       u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                                       u'html_url': u'https://github.com/aromanovich',
                                       u'id': 891264,
                                       u'login': u'aromanovich',
                                       u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                                       u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                                       u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                                       u'site_admin': False,
                                       u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                                       u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                                       u'type': u'User',
                                       u'url': u'https://api.github.com/users/aromanovich'}},
                   u'body': u'',
                   u'changed_files': 1,
                   u'closed_at': None,
                   u'comments': 0,
                   u'comments_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/6/comments',
                   u'commits': 128,
                   u'commits_url': u'https://github.com/aromanovich/yearinpictures/pull/6/commits',
                   u'created_at': u'2013-10-20T09:56:20Z',
                   u'deletions': 0,
                   u'diff_url': u'https://github.com/aromanovich/yearinpictures/pull/6.diff',
                   u'head': {u'label': u'aromanovich:test',
                             u'ref': u'test',
                             u'repo': {u'archive_url': u'https://api.github.com/repos/aromanovich/yearinpictures/{archive_format}{/ref}',
                                       u'assignees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/assignees{/user}',
                                       u'blobs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/blobs{/sha}',
                                       u'branches_url': u'https://api.github.com/repos/aromanovich/yearinpictures/branches{/branch}',
                                       u'clone_url': u'https://github.com/aromanovich/yearinpictures.git',
                                       u'collaborators_url': u'https://api.github.com/repos/aromanovich/yearinpictures/collaborators{/collaborator}',
                                       u'comments_url': u'https://api.github.com/repos/aromanovich/yearinpictures/comments{/number}',
                                       u'commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/commits{/sha}',
                                       u'compare_url': u'https://api.github.com/repos/aromanovich/yearinpictures/compare/{base}...{head}',
                                       u'contents_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contents/{+path}',
                                       u'contributors_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contributors',
                                       u'created_at': u'2012-09-23T10:48:14Z',
                                       u'default_branch': u'master',
                                       u'description': None,
                                       u'downloads_url': u'https://api.github.com/repos/aromanovich/yearinpictures/downloads',
                                       u'events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/events',
                                       u'fork': False,
                                       u'forks': 0,
                                       u'forks_count': 0,
                                       u'forks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/forks',
                                       u'full_name': u'aromanovich/yearinpictures',
                                       u'git_commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/commits{/sha}',
                                       u'git_refs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/refs{/sha}',
                                       u'git_tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/tags{/sha}',
                                       u'git_url': u'git://github.com/aromanovich/yearinpictures.git',
                                       u'has_downloads': True,
                                       u'has_issues': True,
                                       u'has_wiki': True,
                                       u'homepage': None,
                                       u'hooks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/hooks',
                                       u'html_url': u'https://github.com/aromanovich/yearinpictures',
                                       u'id': 5921305,
                                       u'issue_comment_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/comments/{number}',
                                       u'issue_events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/events{/number}',
                                       u'issues_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues{/number}',
                                       u'keys_url': u'https://api.github.com/repos/aromanovich/yearinpictures/keys{/key_id}',
                                       u'labels_url': u'https://api.github.com/repos/aromanovich/yearinpictures/labels{/name}',
                                       u'language': u'JavaScript',
                                       u'languages_url': u'https://api.github.com/repos/aromanovich/yearinpictures/languages',
                                       u'master_branch': u'master',
                                       u'merges_url': u'https://api.github.com/repos/aromanovich/yearinpictures/merges',
                                       u'milestones_url': u'https://api.github.com/repos/aromanovich/yearinpictures/milestones{/number}',
                                       u'mirror_url': None,
                                       u'name': u'yearinpictures',
                                       u'notifications_url': u'https://api.github.com/repos/aromanovich/yearinpictures/notifications{?since,all,participating}',
                                       u'open_issues': 1,
                                       u'open_issues_count': 1,
                                       u'owner': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                                                  u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                                                  u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                                                  u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                                                  u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                                                  u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                                                  u'html_url': u'https://github.com/aromanovich',
                                                  u'id': 891264,
                                                  u'login': u'aromanovich',
                                                  u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                                                  u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                                                  u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                                                  u'site_admin': False,
                                                  u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                                                  u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                                                  u'type': u'User',
                                                  u'url': u'https://api.github.com/users/aromanovich'},
                                       u'private': True,
                                       u'pulls_url': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls{/number}',
                                       u'pushed_at': u'2013-11-12T17:33:51Z',
                                       u'releases_url': u'https://api.github.com/repos/aromanovich/yearinpictures/releases{/id}',
                                       u'size': 2140,
                                       u'ssh_url': u'git@github.com:aromanovich/yearinpictures.git',
                                       u'stargazers_count': 0,
                                       u'stargazers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/stargazers',
                                       u'statuses_url': u'https://api.github.com/repos/aromanovich/yearinpictures/statuses/{sha}',
                                       u'subscribers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscribers',
                                       u'subscription_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscription',
                                       u'svn_url': u'https://github.com/aromanovich/yearinpictures',
                                       u'tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/tags',
                                       u'teams_url': u'https://api.github.com/repos/aromanovich/yearinpictures/teams',
                                       u'trees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/trees{/sha}',
                                       u'updated_at': u'2013-11-12T17:33:51Z',
                                       u'url': u'https://api.github.com/repos/aromanovich/yearinpictures',
                                       u'watchers': 0,
                                       u'watchers_count': 0},
                             u'sha': u'47fe2c74f6d46304830ed46afd59a53401b20b78',
                             u'user': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                                       u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                                       u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                                       u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                                       u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                                       u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                                       u'html_url': u'https://github.com/aromanovich',
                                       u'id': 891264,
                                       u'login': u'aromanovich',
                                       u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                                       u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                                       u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                                       u'site_admin': False,
                                       u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                                       u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                                       u'type': u'User',
                                       u'url': u'https://api.github.com/users/aromanovich'}},
                   u'html_url': u'https://github.com/aromanovich/yearinpictures/pull/6',
                   u'id': 9237389,
                   u'issue_url': u'https://github.com/aromanovich/yearinpictures/pull/6',
                   u'merge_commit_sha': u'59cdc076987c82fdc9156b38b85c336df597ee51',
                   u'mergeable': None,
                   u'mergeable_state': u'unknown',
                   u'merged': False,
                   u'merged_at': None,
                   u'merged_by': None,
                   u'milestone': None,
                   u'number': 6,
                   u'patch_url': u'https://github.com/aromanovich/yearinpictures/pull/6.patch',
                   u'review_comment_url': u'/repos/aromanovich/yearinpictures/pulls/comments/{number}',
                   u'review_comments': 0,
                   u'review_comments_url': u'https://github.com/aromanovich/yearinpictures/pull/6/comments',
                   u'state': u'open',
                   u'statuses_url': u'https://api.github.com/repos/aromanovich/yearinpictures/statuses/47fe2c74f6d46304830ed46afd59a53401b20b78',
                   u'title': u'Branch commit',
                   u'updated_at': u'2013-11-12T17:33:51Z',
                   u'url': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls/6',
                   u'user': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                             u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                             u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                             u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                             u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                             u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                             u'html_url': u'https://github.com/aromanovich',
                             u'id': 891264,
                             u'login': u'aromanovich',
                             u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                             u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                             u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                             u'site_admin': False,
                             u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                             u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                             u'type': u'User',
                             u'url': u'https://api.github.com/users/aromanovich'}},
 u'repository': {u'archive_url': u'https://api.github.com/repos/aromanovich/yearinpictures/{archive_format}{/ref}',
                 u'assignees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/assignees{/user}',
                 u'blobs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/blobs{/sha}',
                 u'branches_url': u'https://api.github.com/repos/aromanovich/yearinpictures/branches{/branch}',
                 u'clone_url': u'https://github.com/aromanovich/yearinpictures.git',
                 u'collaborators_url': u'https://api.github.com/repos/aromanovich/yearinpictures/collaborators{/collaborator}',
                 u'comments_url': u'https://api.github.com/repos/aromanovich/yearinpictures/comments{/number}',
                 u'commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/commits{/sha}',
                 u'compare_url': u'https://api.github.com/repos/aromanovich/yearinpictures/compare/{base}...{head}',
                 u'contents_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contents/{+path}',
                 u'contributors_url': u'https://api.github.com/repos/aromanovich/yearinpictures/contributors',
                 u'created_at': u'2012-09-23T10:48:14Z',
                 u'default_branch': u'master',
                 u'description': None,
                 u'downloads_url': u'https://api.github.com/repos/aromanovich/yearinpictures/downloads',
                 u'events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/events',
                 u'fork': False,
                 u'forks': 0,
                 u'forks_count': 0,
                 u'forks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/forks',
                 u'full_name': u'aromanovich/yearinpictures',
                 u'git_commits_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/commits{/sha}',
                 u'git_refs_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/refs{/sha}',
                 u'git_tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/tags{/sha}',
                 u'git_url': u'git://github.com/aromanovich/yearinpictures.git',
                 u'has_downloads': True,
                 u'has_issues': True,
                 u'has_wiki': True,
                 u'homepage': None,
                 u'hooks_url': u'https://api.github.com/repos/aromanovich/yearinpictures/hooks',
                 u'html_url': u'https://github.com/aromanovich/yearinpictures',
                 u'id': 5921305,
                 u'issue_comment_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/comments/{number}',
                 u'issue_events_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues/events{/number}',
                 u'issues_url': u'https://api.github.com/repos/aromanovich/yearinpictures/issues{/number}',
                 u'keys_url': u'https://api.github.com/repos/aromanovich/yearinpictures/keys{/key_id}',
                 u'labels_url': u'https://api.github.com/repos/aromanovich/yearinpictures/labels{/name}',
                 u'language': u'JavaScript',
                 u'languages_url': u'https://api.github.com/repos/aromanovich/yearinpictures/languages',
                 u'master_branch': u'master',
                 u'merges_url': u'https://api.github.com/repos/aromanovich/yearinpictures/merges',
                 u'milestones_url': u'https://api.github.com/repos/aromanovich/yearinpictures/milestones{/number}',
                 u'mirror_url': None,
                 u'name': u'yearinpictures',
                 u'notifications_url': u'https://api.github.com/repos/aromanovich/yearinpictures/notifications{?since,all,participating}',
                 u'open_issues': 1,
                 u'open_issues_count': 1,
                 u'owner': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
                            u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
                            u'followers_url': u'https://api.github.com/users/aromanovich/followers',
                            u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
                            u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
                            u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
                            u'html_url': u'https://github.com/aromanovich',
                            u'id': 891264,
                            u'login': u'aromanovich',
                            u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
                            u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
                            u'repos_url': u'https://api.github.com/users/aromanovich/repos',
                            u'site_admin': False,
                            u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
                            u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
                            u'type': u'User',
                            u'url': u'https://api.github.com/users/aromanovich'},
                 u'private': True,
                 u'pulls_url': u'https://api.github.com/repos/aromanovich/yearinpictures/pulls{/number}',
                 u'pushed_at': u'2013-11-12T17:33:51Z',
                 u'releases_url': u'https://api.github.com/repos/aromanovich/yearinpictures/releases{/id}',
                 u'size': 2140,
                 u'ssh_url': u'git@github.com:aromanovich/yearinpictures.git',
                 u'stargazers_count': 0,
                 u'stargazers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/stargazers',
                 u'statuses_url': u'https://api.github.com/repos/aromanovich/yearinpictures/statuses/{sha}',
                 u'subscribers_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscribers',
                 u'subscription_url': u'https://api.github.com/repos/aromanovich/yearinpictures/subscription',
                 u'svn_url': u'https://github.com/aromanovich/yearinpictures',
                 u'tags_url': u'https://api.github.com/repos/aromanovich/yearinpictures/tags',
                 u'teams_url': u'https://api.github.com/repos/aromanovich/yearinpictures/teams',
                 u'trees_url': u'https://api.github.com/repos/aromanovich/yearinpictures/git/trees{/sha}',
                 u'updated_at': u'2013-11-12T17:33:51Z',
                 u'url': u'https://api.github.com/repos/aromanovich/yearinpictures',
                 u'watchers': 0,
                 u'watchers_count': 0},
 u'sender': {u'avatar_url': u'https://1.gravatar.com/avatar/e85b7ebc8dacdaa850d3999f7c676343?d=https%3A%2F%2Fidenticons.github.com%2F117220178921ce5a8073addc64382fd3.png&r=x',
             u'events_url': u'https://api.github.com/users/aromanovich/events{/privacy}',
             u'followers_url': u'https://api.github.com/users/aromanovich/followers',
             u'following_url': u'https://api.github.com/users/aromanovich/following{/other_user}',
             u'gists_url': u'https://api.github.com/users/aromanovich/gists{/gist_id}',
             u'gravatar_id': u'e85b7ebc8dacdaa850d3999f7c676343',
             u'html_url': u'https://github.com/aromanovich',
             u'id': 891264,
             u'login': u'aromanovich',
             u'organizations_url': u'https://api.github.com/users/aromanovich/orgs',
             u'received_events_url': u'https://api.github.com/users/aromanovich/received_events',
             u'repos_url': u'https://api.github.com/users/aromanovich/repos',
             u'site_admin': False,
             u'starred_url': u'https://api.github.com/users/aromanovich/starred{/owner}{/repo}',
             u'subscriptions_url': u'https://api.github.com/users/aromanovich/subscriptions',
             u'type': u'User',
             u'url': u'https://api.github.com/users/aromanovich'}}

PULL_REQUEST_HOOK_CALL_JSON = json.dumps(PULL_REQUEST_HOOK_CALL_DATA)
