"""empty message

Revision ID: 1531599e3534
Revises: 5590ef356b4f
Create Date: 2013-12-14 21:46:13.520346

"""

# revision identifiers, used by Alembic.
revision = '1531599e3534'
down_revision = '5590ef356b4f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'gh_commit_ref',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.add_column('user', sa.Column('email', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.alter_column('build', 'gh_commit_ref',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    ### end Alembic commands ###
