"""empty message

Revision ID: 390c1805c002
Revises: 4bbfdf089fbc
Create Date: 2014-01-21 23:53:26.082845

"""

# revision identifiers, used by Alembic.
revision = '390c1805c002'
down_revision = '4bbfdf089fbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hook_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=250, collation='utf8_bin'), nullable=False),
    sa.ForeignKeyConstraint(['hook_id'], ['hook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hook_id', 'path', name='unique_tracked_file_within_hook')
    )
    op.add_column(u'hook', sa.Column('install_script', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'hook', 'install_script')
    op.drop_table('tracked_file')
    ### end Alembic commands ###
