"""empty message

Revision ID: 4bbfdf089fbc
Revises: 2cc431e5815b
Create Date: 2014-01-07 23:46:14.694649

"""

# revision identifiers, used by Alembic.
revision = '4bbfdf089fbc'
down_revision = '2cc431e5815b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('allows_management', sa.Boolean(), nullable=False))
    op.alter_column('project_members', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('project_members', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_members', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('project_members', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('project_members', 'allows_management')
    ### end Alembic commands ###
